<<<<<<< HEAD
version: '3.7'

services:
  devit-mysql:
    container_name: devit_db
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: devit
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: devit
    secrets:
      - mysql_secret
    ports:
      - 3306:3306
    volumes:
      - "mysql_data:/var/lib/mysql"
  
secrets:
  mysql_secret:
    file: mysql_secret

volumes:
=======
version: '3.7'

services:
  devit-mysql:
    container_name: devit_db
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: devit
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: devit
    secrets:
      - mysql_secret
    ports:
      - 3306:3306
    volumes:
      - "mysql_data:/var/lib/mysql"
  
secrets:
  mysql_secret:
    file: mysql_secret

volumes:
>>>>>>> branch 'frontend' of https://lab.ssafy.com/s03-webmobile1-sub2/s03p12a101.git
  mysql_data: